### ISSUE TITLE
Setup email configuration for localhost smtp

### ISSUE THREAD

**Issue by jaugustin** [fzaninotto/uptime#215]
Hi,

I try to setup my uptime to send email with a local smtp installed on the server, and a I got a hard time to do it.

To send email to local smtp it should be as simple as no setup, but that's not working because of the `default.yml` configuration that override it.

To send email with local smtp you have to use those settings :

``` yaml
email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:         # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:            
#      user:          # The email account username, e.g. 'username@gmail.com'
#      pass:          # The email account password, e.G. 'password'
```

I think we should change the default configuration to an empty `transport` parameter 
Or put some documentation for this, because pointing to https://github.com/andris9/nodemailer documentation didn't help very much ;)

@fzaninotto what do you think ?
